In [22]:
import pandas as pd

In [23]:
dataset = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

In [24]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder

In [25]:
te = TransactionEncoder()
te_array = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_array, columns=te.columns_)
df

,Apple,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Unicorn,Yogurt
0,False,False,False,True,False,True,True,True,True,False,True
1,False,False,True,True,False,True,False,True,True,False,True
2,True,False,False,True,False,True,True,False,False,False,False
3,False,True,False,False,False,True,True,False,False,True,True
4,False,True,False,True,True,True,False,False,True,False,False

In [30]:
from mlxtend.frequent_patterns import apriori
frequent_sets = apriori(df, min_support=0.6, use_colnames= True)
print(frequent_sets)

    support                                itemsets
0       0.8                       frozenset({Eggs})
1       1.0               frozenset({Kidney Beans})
2       0.6                       frozenset({Milk})
3       0.6                      frozenset({Onion})
4       0.6                     frozenset({Yogurt})
5       0.8         frozenset({Kidney Beans, Eggs})
6       0.6                frozenset({Onion, Eggs})
7       0.6         frozenset({Milk, Kidney Beans})
8       0.6        frozenset({Onion, Kidney Beans})
9       0.6       frozenset({Yogurt, Kidney Beans})
10      0.6  frozenset({Kidney Beans, Onion, Eggs})

In [31]:
from mlxtend.frequent_patterns import association_rules
rules = association_rules(frequent_sets,metric="confidence", min_threshold=0.8)
print(rules)

                        antecedents                      consequents  \
0         frozenset({Kidney Beans})                frozenset({Eggs})
1                 frozenset({Eggs})        frozenset({Kidney Beans})
2                frozenset({Onion})                frozenset({Eggs})
3                 frozenset({Milk})        frozenset({Kidney Beans})
4                frozenset({Onion})        frozenset({Kidney Beans})
5               frozenset({Yogurt})        frozenset({Kidney Beans})
6  frozenset({Onion, Kidney Beans})                frozenset({Eggs})
7          frozenset({Onion, Eggs})        frozenset({Kidney Beans})
8                frozenset({Onion})  frozenset({Kidney Beans, Eggs})

   antecedent support  consequent support  support  confidence  lift  \
0                 1.0                 0.8      0.8         0.8  1.00
1                 0.8                 1.0      0.8         1.0  1.00
2                 0.6                 0.8      0.6         1.0  1.25
3                 0.6                 1.0      0.6         1.0  1.00
4                 0.6                 1.0      0.6         1.0  1.00
5                 0.6                 1.0      0.6         1.0  1.00
6                 0.6                 0.8      0.6         1.0  1.25
7                 0.6                 1.0      0.6         1.0  1.00
8                 0.6                 0.8      0.6         1.0  1.25

   representativity  leverage  conviction  zhangs_metric  jaccard  certainty  \
0               1.0      0.00         1.0            0.0     0.80        0.0
1               1.0      0.00         inf            0.0     0.80        0.0
2               1.0      0.12         inf            0.5     0.75        1.0
3               1.0      0.00         inf            0.0     0.60        0.0
4               1.0      0.00         inf            0.0     0.60        0.0
5               1.0      0.00         inf            0.0     0.60        0.0
6               1.0      0.12         inf            0.5     0.75        1.0
7               1.0      0.00         inf            0.0     0.60        0.0
8               1.0      0.12         inf            0.5     0.75        1.0

   kulczynski
0       0.900
1       0.900
2       0.875
3       0.800
4       0.800
5       0.800
6       0.875
7       0.800
8       0.875

c:\Users\Acer\anaconda3\envs\rohit_gurung\Lib\site-packages\mlxtend\frequent_patterns\association_rules.py:186: RuntimeWarning: invalid value encountered in divide
  cert_metric = np.where(certainty_denom == 0, 0, certainty_num / certainty_denom)

In [32]:
rules = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]
print(rules)

                        antecedents                      consequents  support  \
0         frozenset({Kidney Beans})                frozenset({Eggs})      0.8
1                 frozenset({Eggs})        frozenset({Kidney Beans})      0.8
2                frozenset({Onion})                frozenset({Eggs})      0.6
3                 frozenset({Milk})        frozenset({Kidney Beans})      0.6
4                frozenset({Onion})        frozenset({Kidney Beans})      0.6
5               frozenset({Yogurt})        frozenset({Kidney Beans})      0.6
6  frozenset({Onion, Kidney Beans})                frozenset({Eggs})      0.6
7          frozenset({Onion, Eggs})        frozenset({Kidney Beans})      0.6
8                frozenset({Onion})  frozenset({Kidney Beans, Eggs})      0.6

   confidence  lift
0         0.8  1.00
1         1.0  1.00
2         1.0  1.25
3         1.0  1.00
4         1.0  1.00
5         1.0  1.00
6         1.0  1.25
7         1.0  1.00
8         1.0  1.25

In [34]:
for i, item in rules.iterrows():
    if item.lift > 1:
        print(item)

antecedents    frozenset({Onion})
consequents     frozenset({Eggs})
support                       0.6
confidence                    1.0
lift                         1.25
Name: 2, dtype: object
antecedents    frozenset({Onion, Kidney Beans})
consequents                   frozenset({Eggs})
support                                     0.6
confidence                                  1.0
lift                                       1.25
Name: 6, dtype: object
antecedents                 frozenset({Onion})
consequents    frozenset({Kidney Beans, Eggs})
support                                    0.6
confidence                                 1.0
lift                                      1.25
Name: 8, dtype: object

In [36]:
rules["antecedent_len"] = rules["antecedents"].apply(lambda x: len(x))
rules

,antecedents,consequents,support,confidence,lift,antecedent_len
0,frozenset({Kidney Beans}),frozenset({Eggs}),0.8,0.8,1.00,1
1,frozenset({Eggs}),frozenset({Kidney Beans}),0.8,1.0,1.00,1
2,frozenset({Onion}),frozenset({Eggs}),0.6,1.0,1.25,1
3,frozenset({Milk}),frozenset({Kidney Beans}),0.6,1.0,1.00,1
4,frozenset({Onion}),frozenset({Kidney Beans}),0.6,1.0,1.00,1
5,frozenset({Yogurt}),frozenset({Kidney Beans}),0.6,1.0,1.00,1
6,"frozenset({Onion, Kidney Beans})",frozenset({Eggs}),0.6,1.0,1.25,2
7,"frozenset({Onion, Eggs})",frozenset({Kidney Beans}),0.6,1.0,1.00,2
8,frozenset({Onion}),"frozenset({Kidney Beans, Eggs})",0.6,1.0,1.25,1

In [37]:
rules[rules["antecedents"] == {'Onion', 'Eggs'}]

,antecedents,consequents,support,confidence,lift,antecedent_len
7,"frozenset({Onion, Eggs})",frozenset({Kidney Beans}),0.6,1.0,1.0,2