In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl

print(f"Pandas version: {pd.__version__}")
print(f"NumPy version: {np.__version__}")
print(f"Matplotlib version: {mpl.__version__}")

Pandas version: 3.0.2
NumPy version: 2.4.4
Matplotlib version: 3.10.9

In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

columns = ["sepal_length", "sepal_width", "petal_length", "petal_width", "species"]

df = pd.read_csv(url, names=columns)

print("Dataset imported successfully.")
df.head(5)

Dataset imported successfully.

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [4]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

In [5]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [6]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [7]:
df_cleaned = df.copy()
# Numerical columns
numeric_columns = ["sepal_length", "sepal_width", "petal_length", "petal_width"]

# Fill missing numerical values with median
for column in numeric_columns:
    df_cleaned[column] = df_cleaned[column].fillna(df_cleaned[column].median())

# Fill missing categorical values with mode
df_cleaned["species"] = df_cleaned["species"].fillna(df_cleaned["species"].mode()[0])

# Check missing values after imputation
print("\nMissing values after imputation:")
print(df_cleaned.isnull().sum())

Missing values after imputation:
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [8]:
# Normalize numerical columns to a scale between 0 and 1

numeric_columns = ["sepal_length", "sepal_width", "petal_length", "petal_width"]

df_normalized = df_cleaned.copy()

df_normalized[numeric_columns] = (
    df_normalized[numeric_columns] - df_normalized[numeric_columns].min()
) / (
    df_normalized[numeric_columns].max() - df_normalized[numeric_columns].min()
)

df_normalized.head(5)

   sepal_length  sepal_width  petal_length  petal_width      species
0      0.222222     0.625000      0.067797     0.041667  Iris-setosa
1      0.166667     0.416667      0.067797     0.041667  Iris-setosa
2      0.111111     0.500000      0.050847     0.041667  Iris-setosa
3      0.083333     0.458333      0.084746     0.041667  Iris-setosa
4      0.194444     0.666667      0.067797     0.041667  Iris-setosa

In [9]:
# Encoding: Convert categorical species labels into numbers
df_transformed = df_cleaned.copy()
df_transformed["species_code"] = pd.factorize(df_transformed["species"])[0]
df_transformed[["species", "species_code"]].head(5)

       species  species_code
0  Iris-setosa             0
1  Iris-setosa             0
2  Iris-setosa             0
3  Iris-setosa             0
4  Iris-setosa             0

In [10]:
# OLAP Operation 1: Slicing
from IPython.display import display

slicing_result = df_transformed[df_transformed["species"] == "Iris-setosa"]

print("Slicing Result: Iris-setosa flowers only")
display(slicing_result.head(5))

Slicing Result: Iris-setosa flowers only

,sepal_length,sepal_width,petal_length,petal_width,species,species_code
0,5.1,3.5,1.4,0.2,Iris-setosa,0
1,4.9,3.0,1.4,0.2,Iris-setosa,0
2,4.7,3.2,1.3,0.2,Iris-setosa,0
3,4.6,3.1,1.5,0.2,Iris-setosa,0
4,5.0,3.6,1.4,0.2,Iris-setosa,0

In [11]:
# OLAP Operation 2: Dicing
from IPython.display import display
dicing_result = df_transformed[
    (df_transformed["species"] == "Iris-setosa") &
    (df_transformed["sepal_length"] > 5.0)
]
print("Dicing Result: Iris-setosa flowers with sepal_length greater than 5.0")
display(dicing_result.head(5))

Dicing Result: Iris-setosa flowers with sepal_length greater than 5.0

,sepal_length,sepal_width,petal_length,petal_width,species,species_code
0,5.1,3.5,1.4,0.2,Iris-setosa,0
5,5.4,3.9,1.7,0.4,Iris-setosa,0
10,5.4,3.7,1.5,0.2,Iris-setosa,0
14,5.8,4.0,1.2,0.2,Iris-setosa,0
15,5.7,4.4,1.5,0.4,Iris-setosa,0

In [12]:
# OLAP Operation 3: Roll-up
from IPython.display import display
numeric_columns = ["sepal_length", "sepal_width", "petal_length", "petal_width"]
rollup_result = df_transformed.groupby("species")[numeric_columns].mean()

print("Roll-up Result: Average measurements grouped by species")
display(rollup_result)

Roll-up Result: Average measurements grouped by species

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa             5.006        3.418         1.464        0.244
Iris-versicolor         5.936        2.770         4.260        1.326
Iris-virginica          6.588        2.974         5.552        2.026

In [13]:
# OLAP Operation 4: Drill-down
from IPython.display import display
df_transformed["petal_size_category"] = pd.cut(
    df_transformed["petal_length"],
    bins=[0, 2, 5, 7],
    labels=["Small", "Medium", "Large"]
)
drilldown_result = df_transformed.groupby(
    ["species", "petal_size_category"],
    observed=True
)[numeric_columns].mean()
print("Drill-down Result: Average measurements grouped by species and petal size category")
display(drilldown_result)

Drill-down Result: Average measurements grouped by species and petal size category

                                     sepal_length  sepal_width  petal_length  \
species         petal_size_category
Iris-setosa     Small                    5.006000     3.418000      1.464000
Iris-versicolor Medium                   5.934694     2.771429      4.242857
                Large                    6.000000     2.700000      5.100000
Iris-virginica  Medium                   5.900000     2.666667      4.866667
                Large                    6.739024     3.041463      5.702439

                                     petal_width
species         petal_size_category
Iris-setosa     Small                   0.244000
Iris-versicolor Medium                  1.320408
                Large                   1.600000
Iris-virginica  Medium                  1.811111
                Large                   2.073171

In [14]:
# Step 1: Data Integration using concat
from IPython.display import display
df_part1 = df.iloc[:75]
df_part2 = df.iloc[75:]

df_integrated_concat = pd.concat([df_part1, df_part2], ignore_index=True)
print("Data Integration using concat completed.")
print("Original dataset shape:", df.shape)
print("Integrated dataset shape:", df_integrated_concat.shape)

display(df_integrated_concat.head(5))

Data Integration using concat completed.
Original dataset shape: (150, 5)
Integrated dataset shape: (150, 5)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [15]:
# Step 2: Data Integration using merge
species_info = pd.DataFrame({
    "species": ["Iris-setosa", "Iris-versicolor", "Iris-virginica"],
    "flower_group": ["Group A", "Group B", "Group C"]
})
df_integrated_merge = pd.merge(df_integrated_concat, species_info, on="species", how="left")
print("Data Integration using merge completed.")

display(df_integrated_merge.head(5))

Data Integration using merge completed.

,sepal_length,sepal_width,petal_length,petal_width,species,flower_group
0,5.1,3.5,1.4,0.2,Iris-setosa,Group A
1,4.9,3.0,1.4,0.2,Iris-setosa,Group A
2,4.7,3.2,1.3,0.2,Iris-setosa,Group A
3,4.6,3.1,1.5,0.2,Iris-setosa,Group A
4,5.0,3.6,1.4,0.2,Iris-setosa,Group A

In [16]:
# Step 3: Feature Selection
selected_features = ["sepal_length", "sepal_width", "petal_length", "petal_width"]

X = df_cleaned[selected_features]
y = df_cleaned["species"]

print("Selected features for analysis:")
print(selected_features)

display(X.head(5))

Selected features for analysis:
['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [17]:
# Step 5: Visualization
for species_name in df_cleaned["species"].unique():
    species_data = df_cleaned[df_cleaned["species"] == species_name]
    plt.scatter(
        species_data["petal_length"],
        species_data["petal_width"],
        label=species_name
    )
plt.xlabel("Petal Length")
plt.ylabel("Petal Width")
plt.title("Petal Length vs Petal Width by Iris Species")
plt.legend()
plt.show()

NameError: name 'plt' is not defined

In [ ]:
# Working with Datasets
# Saving the Iris dataset as CSV and JSON files

df_cleaned.to_csv("iris_dataset.csv", index=False)

df_cleaned.to_json("iris_dataset.json", orient="records")

print("CSV and JSON files saved successfully.")

CSV and JSON files saved successfully.

In [ ]:
# Reading Data from Files: CSV and JSON

from IPython.display import display
# Reading a CSV file
df_csv = pd.read_csv("iris_dataset.csv")

# Reading a JSON file
df_json = pd.read_json("iris_dataset.json")

# Quick check of the first 5 rows from CSV
print("First 5 rows from CSV file:")
display(df_csv.head())

# Quick check of the first 5 rows from JSON
print("First 5 rows from JSON file:")
display(df_json.head())

First 5 rows from CSV file:

,sepal_length,sepal_width,petal_length,petal_width,species,flower_group
0,5.1,3.5,1.4,0.2,Iris-setosa,Group A
1,4.9,3.0,1.4,0.2,Iris-setosa,Group A
2,4.7,3.2,1.3,0.2,Iris-setosa,Group A
3,4.6,3.1,1.5,0.2,Iris-setosa,Group A
4,5.0,3.6,1.4,0.2,Iris-setosa,Group A

First 5 rows from JSON file:

,sepal_length,sepal_width,petal_length,petal_width,species,flower_group
0,5.1,3.5,1.4,0.2,Iris-setosa,Group A
1,4.9,3.0,1.4,0.2,Iris-setosa,Group A
2,4.7,3.2,1.3,0.2,Iris-setosa,Group A
3,4.6,3.1,1.5,0.2,Iris-setosa,Group A
4,5.0,3.6,1.4,0.2,Iris-setosa,Group A

In [ ]:
# Generating Synthetic Data for Testing
import pandas as pd
import numpy as np
import json
from io import StringIO
from IPython.display import display
# 1. Generating synthetic numerical data with NumPy
data_size = 100
data = {
    "ID": np.arange(1, data_size + 1),
    "Age": np.random.randint(18, 70, size=data_size),
    "Salary": np.random.normal(50000, 15000, size=data_size).round(2),
    "Purchase_Count": np.random.poisson(5, size=data_size)
}
df_synthetic = pd.DataFrame(data)
print("Synthetic DataFrame:")
display(df_synthetic.head(5))

# 2. Saving and Reading as JSON
json_data = df_synthetic.to_json(orient="records")
# Load back from JSON using StringIO
df_from_json = pd.read_json(StringIO(json_data))
print("Data loaded back from JSON:")
display(df_from_json.head(5))

Synthetic DataFrame:

   ID  Age    Salary  Purchase_Count
0   1   62  58306.81               9
1   2   39  55139.46               5
2   3   60  30954.53               6
3   4   37  61054.41               6
4   5   24  60670.28               3

Data loaded back from JSON:

   ID  Age    Salary  Purchase_Count
0   1   62  58306.81               9
1   2   39  55139.46               5
2   3   60  30954.53               6
3   4   37  61054.41               6
4   5   24  60670.28               3

In [ ]:
# Feature Selection

selected_features = ["sepal_length", "sepal_width", "petal_length", "petal_width"]

X = df_cleaned[selected_features]
y = df_cleaned["species"]

print("Selected Features:")
print(selected_features)

display(X.head(5))

Selected Features:
['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [ ]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\Users\Acer\anaconda3\envs\rohit_gurung\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\Acer\anaconda3\envs\rohit_gurung\Lib\site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\Acer\anaconda3\envs\rohit_gurung\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\Users\Acer\anaconda3\envs\rohit_gurung\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\Users\Acer\anaconda3\envs\rohit_gurung\Lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [20]:
# Data Mining: Applying K-Means Clustering Algorithm

from sklearn.cluster import KMeans
from IPython.display import display

# Select numerical columns
numeric_columns = ["sepal_length", "sepal_width", "petal_length", "petal_width"]

# Make a copy of cleaned data
df_clustered = df_cleaned.copy()

# Make sure numerical columns are numeric
for column in numeric_columns:
    df_clustered[column] = pd.to_numeric(df_clustered[column], errors="coerce")

# Fill any missing numerical values with median
for column in numeric_columns:
    df_clustered[column] = df_clustered[column].fillna(df_clustered[column].median())

# Select features for clustering
X = df_clustered[numeric_columns]

# Create K-Means model with 3 clusters
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)

# Add cluster result to dataset
df_clustered["cluster"] = kmeans.fit_predict(X)

print("K-Means clustering completed successfully.")
display(df_clustered.head(5))

K-Means clustering completed successfully.

c:\Users\Acer\anaconda3\envs\rohit_gurung\Lib\site-packages\sklearn\cluster\_kmeans.py:1425: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

   sepal_length  sepal_width  petal_length  petal_width      species  cluster
0           5.1          3.5           1.4          0.2  Iris-setosa        1
1           4.9          3.0           1.4          0.2  Iris-setosa        1
2           4.7          3.2           1.3          0.2  Iris-setosa        1
3           4.6          3.1           1.5          0.2  Iris-setosa        1
4           5.0          3.6           1.4          0.2  Iris-setosa        1

In [21]:
# Evaluation / Interpretation

from IPython.display import display

# Show average values for each cluster
cluster_summary = df_clustered.groupby("cluster")[numeric_columns].mean()

print("Cluster Summary:")
display(cluster_summary)

print("Interpretation:")
print("The K-Means algorithm grouped the iris flowers into three clusters.")
print("The cluster summary shows the average measurements for each cluster.")
print("Petal length and petal width are useful features because they help separate the flower groups.")
print("Flowers with smaller petal measurements are separated from flowers with larger petal measurements.")
print("This shows that the Iris dataset has clear patterns based on flower measurements.")

Cluster Summary:

         sepal_length  sepal_width  petal_length  petal_width
cluster
0            5.901613     2.748387      4.393548     1.433871
1            5.006000     3.418000      1.464000     0.244000
2            6.850000     3.073684      5.742105     2.071053

Interpretation:
The K-Means algorithm grouped the iris flowers into three clusters.
The cluster summary shows the average measurements for each cluster.
Petal length and petal width are useful features because they help separate the flower groups.
Flowers with smaller petal measurements are separated from flowers with larger petal measurements.
This shows that the Iris dataset has clear patterns based on flower measurements.